spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    #    url: jdbc:h2:mem:test
    #    username: sa
    #    password:
    #    driverClassName: org.h2.Driver
    url: jdbc:mysql://localhost:3306/there?serverTimezone=Asia/Seoul
    username: test
    password: Q1w2e3r4
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true